---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: example-com
  namespace: default
spec:
  secretName: example-com-tls
  issueRef:
    name: ca-issuer
    kind: Issuer
  commonName: example.com
  dnsNames:
    - www.example.com

