---
apiVersion: certmanager.k8s.io/v1aplha1
kind: Issuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging.api.letsencrypt.org/directory
    email: henry_chia21@hotmail.co.uk
    privateKeySecretRef:
      name: letsencrypt-staging
    http01: {}
